# -*- coding: utf-8 -*-
"""EnSOn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jmc0cm44UD812LzaIhEjN2-SYeqEdlH2
"""

# HÜCRE 1: KURULUM & DRIVE BAĞLANTISI


import os
from google.colab import drive

# Drive'ı bağla
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# Gerekli kütüphaneleri kur
print("📦 Kütüphaneler kuruluyor...")
!pip install kaggle insightface onnxruntime-gpu timm -q

import json
import cv2
import random
import io
import numpy as np
import torch
import torch.nn as nn
import timm
from pathlib import Path
from PIL import Image
from tqdm import tqdm
from insightface.app import FaceAnalysis
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, WeightedRandomSampler
from sklearn.metrics import roc_auc_score, accuracy_score

# GPU kontrolü
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f" Cihaz: {device}")
if device.type == 'cuda':
    print(f" GPU: {torch.cuda.get_device_name(0)}")
    print(f" GPU RAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print(" GPU bulunamadı! Eğitim çok yavaş olacak.")

print("\n Kurulum tamamlandı!")

# DFDC Veri Seti İndirme


DFDC_RAW_DIR = '/content/dfdc_raw'
DFDC_SAMPLE_DIR = os.path.join(DFDC_RAW_DIR, 'train_sample_videos')

if not os.path.exists(DFDC_SAMPLE_DIR):
    print(" DFDC veri seti indiriliyor...")

    # Kaggle API kurulumu
    !mkdir -p ~/.kaggle
    !cp kaggle.json ~/.kaggle/ 2>/dev/null
    !chmod 600 ~/.kaggle/kaggle.json

    # Veri setini indir
    !kaggle competitions download -c deepfake-detection-challenge

    # Zip'i çıkar
    print(" Zip çıkarılıyor (birkaç dakika sürebilir)...")
    !unzip -q deepfake-detection-challenge.zip -d {DFDC_RAW_DIR}

    print(" Veri seti indirildi!")
else:
    print(f" DFDC verisi zaten mevcut: {DFDC_SAMPLE_DIR}")

# metadata var mı
METADATA_PATH = os.path.join(DFDC_SAMPLE_DIR, 'metadata.json')
if os.path.exists(METADATA_PATH):
    with open(METADATA_PATH, 'r') as f:
        metadata = json.load(f)
    print(f" Toplam {len(metadata)} video bulundu.")
    fake_count = sum(1 for v in metadata.values() if v['label'] == 'FAKE')
    real_count = len(metadata) - fake_count
    print(f"   FAKE: {fake_count} | REAL: {real_count}")
else:
    print(f" metadata.json bulunamadı: {METADATA_PATH}")

#  Yüz Çıkarma (InsightFace)


FACES_DIR = '/content/dfdc_faces_v2'
DRIVE_FACES_BACKUP = '/content/drive/MyDrive/dfdc_faces_v2_backup.zip'
FRAMES_PER_VIDEO = 32  # Her videodan 32 kare al

if os.path.exists(os.path.join(FACES_DIR, 'train')):
    print(f" Yüzler zaten mevcut: {FACES_DIR}")
    print("   Bu hücreyi atlayabilirsin.")

elif os.path.exists(DRIVE_FACES_BACKUP):
    # Drive'dan geri yükle
    print(f" Yüzler Drive yedeğinden geri yükleniyor...")
    print(f"   Kaynak: {DRIVE_FACES_BACKUP}")
    !unzip -q "{DRIVE_FACES_BACKUP}" -d /content/
    print(" Yüzler Drive'dan geri yüklendi!")

else:
    # Sıfırdan yüz çıkar
    print("="*50)
    print(" YÜZ ÇIKARMA BAŞLIYOR")
    print("="*50)

    METADATA_PATH = os.path.join(DFDC_SAMPLE_DIR, 'metadata.json')
    with open(METADATA_PATH, 'r') as f:
        metadata = json.load(f)

    # %80 Eğitim, %20 Validation
    all_videos = list(metadata.keys())
    random.seed(42)
    random.shuffle(all_videos)
    split_idx = int(len(all_videos) * 0.8)
    train_vids = set(all_videos[:split_idx])

    # InsightFace yüz algılayıcı
    print(" InsightFace yükleniyor...")
    face_app = FaceAnalysis(
        name='buffalo_l',
        providers=['CUDAExecutionProvider', 'CPUExecutionProvider']
    )
    face_app.prepare(ctx_id=0, det_size=(640, 640))

    video_files = list(Path(DFDC_SAMPLE_DIR).glob('*.mp4'))
    print(f" {len(video_files)} video işlenecek, her birinden {FRAMES_PER_VIDEO} kare...\n")

    total_faces_saved = 0

    for video_path in tqdm(video_files, desc="Yüzler Çıkarılıyor"):
        filename = video_path.name
        if filename not in metadata:
            continue

        label = metadata[filename]['label']  # "FAKE" veya "REAL"
        split_name = 'train' if filename in train_vids else 'val'

        save_dir = os.path.join(FACES_DIR, split_name, label, video_path.stem)
        os.makedirs(save_dir, exist_ok=True)

        cap = cv2.VideoCapture(str(video_path))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        if total_frames <= 0:
            cap.release()
            continue

        positions = np.linspace(0, total_frames - 1, FRAMES_PER_VIDEO, dtype=int)
        saved_count = 0

        for pos in positions:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(pos))
            ret, frame = cap.read()
            if not ret:
                continue

            faces = face_app.get(frame)
            if not faces:
                continue

            face = max(faces, key=lambda x: (x.bbox[2]-x.bbox[0])*(x.bbox[3]-x.bbox[1]))
            bbox = face.bbox.astype(int)

            size = int(max(bbox[2]-bbox[0], bbox[3]-bbox[1]) * 1.5)
            cx, cy = (bbox[0]+bbox[2])//2, (bbox[1]+bbox[3])//2
            x1 = max(0, cx - size//2)
            y1 = max(0, cy - size//2)
            x2 = min(frame.shape[1], x1 + size)
            y2 = min(frame.shape[0], y1 + size)
            cropped = frame[y1:y2, x1:x2]

            if cropped.size > 0:
                resized = cv2.resize(cropped, (256, 256))
                cv2.imwrite(f"{save_dir}/f_{saved_count:03d}.png", resized)
                saved_count += 1

        total_faces_saved += saved_count
        cap.release()

    print(f"\n Yüz çıkarma tamamlandı! Toplam {total_faces_saved} yüz resmi.")

    # Drive'a yedekle
    print(f"\n Yüzler Drive'a yedekleniyor...")
    !zip -q -r "{DRIVE_FACES_BACKUP}" "{FACES_DIR}"
    print(f" Yedekleme tamamlandı: {DRIVE_FACES_BACKUP}")

# Sınıf dağılımını göster
print("\n Veri seti dağılımı:")
for split in ['train', 'val']:
    for label in ['FAKE', 'REAL']:
        path = os.path.join(FACES_DIR, split, label)
        if os.path.exists(path):
            count = sum(len(files) for _, _, files in os.walk(path))
            print(f"   {split}/{label}: {count} resim")

# Eğitim Hazırlık


FACES_DIR = '/content/dfdc_faces_v2'
TRAIN_DIR = os.path.join(FACES_DIR, 'train')
VAL_DIR = os.path.join(FACES_DIR, 'val')
SAVE_PATH = '/content/drive/MyDrive/dfdc_model_v2_best.pth'
CHECKPOINT_PATH = '/content/drive/MyDrive/dfdc_v2_checkpoint.pth'

# Deepfake'e Özel Augmentation Sınıfları

class JPEGCompression:
    """Rastgele JPEG sıkıştırma — deepfake sosyal medya bozulmalarını simüle eder"""
    def __init__(self, quality_range=(30, 95)):
        self.quality_range = quality_range

    def __call__(self, img):
        if random.random() < 0.5:
            quality = random.randint(*self.quality_range)
            buffer = io.BytesIO()
            img.save(buffer, format='JPEG', quality=quality)
            buffer.seek(0)
            img = Image.open(buffer).convert('RGB')
        return img


class RandomDownscale:
    """Rastgele küçült-büyüt — WhatsApp/Instagram çözünürlük kaybını simüle eder"""
    def __init__(self, scale_range=(0.5, 0.9)):
        self.scale_range = scale_range

    def __call__(self, img):
        if random.random() < 0.3:
            w, h = img.size
            scale = random.uniform(*self.scale_range)
            small = img.resize((int(w * scale), int(h * scale)), Image.BILINEAR)
            img = small.resize((w, h), Image.BILINEAR)
        return img


class LabelSmoothingBCELoss(nn.Module):
    """Label Smoothing: 0→0.05, 1→0.95 — aşırı güvenli tahminleri önler"""
    def __init__(self, smoothing=0.1):
        super().__init__()
        self.smoothing = smoothing
        self.bce = nn.BCEWithLogitsLoss()

    def forward(self, pred, target):
        target_smooth = target * (1 - self.smoothing) + 0.5 * self.smoothing
        return self.bce(pred, target_smooth)


# Augmentation Pipeline

train_tf = transforms.Compose([
    transforms.RandomResizedCrop(256, scale=(0.75, 1.0)),
    transforms.RandomHorizontalFlip(),
    JPEGCompression(quality_range=(30, 95)),
    RandomDownscale(scale_range=(0.5, 0.9)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
    transforms.GaussianBlur(kernel_size=(3, 7), sigma=(0.1, 3.0)),
    transforms.RandomGrayscale(p=0.05),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    transforms.RandomErasing(p=0.1),
])

val_tf = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Veri Yükleme

print(" Veriler yükleniyor...")
train_dataset = datasets.ImageFolder(TRAIN_DIR, transform=train_tf)
val_dataset = datasets.ImageFolder(VAL_DIR, transform=val_tf)

print(f" Sınıf eşleşmeleri: {train_dataset.class_to_idx}")
fake_idx = train_dataset.class_to_idx.get('FAKE', 0)

# Binary hedefler
train_binary = [1 if label == fake_idx else 0 for label in train_dataset.targets]
n_real = train_binary.count(0)
n_fake = train_binary.count(1)
print(f" Eğitim: {n_real} GERÇEK + {n_fake} SAHTE = {n_real + n_fake} toplam")

# Sınıf dengeleme
class_counts = [max(n_real, 1), max(n_fake, 1)]
class_weights = [1.0 / c for c in class_counts]
sample_weights = [class_weights[label] for label in train_binary]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_dataset, batch_size=16, sampler=sampler, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2, pin_memory=True)

# Model Oluşturma

print("\n EfficientNet-B4 oluşturuluyor (ImageNet ağırlıkları)...")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = timm.create_model('efficientnet_b4', pretrained=True, num_classes=1).to(device)

#  Her şeyi dondur, sadece classifier aç
for param in model.parameters():
    param.requires_grad = False
for param in model.classifier.parameters():
    param.requires_grad = True

criterion = LabelSmoothingBCELoss(smoothing=0.1)

print(f" Model hazır! Cihaz: {device}")
print(f" Model kaydedilecek: {SAVE_PATH}")

#  Model Eğitimi


#   HÜCRE 5: MODEL EĞİTİMİ

TOTAL_EPOCHS = 20
best_auc = 0.0
patience = 5
early_stop_counter = 0
history = []
start_epoch = 0

#  Checkpoint'tan devam et
if os.path.exists(CHECKPOINT_PATH):
    print(" Önceki checkpoint bulundu! Kaldığı yerden devam ediliyor...")
    checkpoint = torch.load(CHECKPOINT_PATH, map_location=device)
    model.load_state_dict(checkpoint['model_state'])
    start_epoch = checkpoint['epoch']
    best_auc = checkpoint.get('best_auc', 0.0)
    early_stop_counter = checkpoint.get('early_stop_counter', 0)
    history = checkpoint.get('history', [])
    print(f"   Epoch {start_epoch}'dan devam ediliyor (En iyi AUC: {best_auc:.4f})")

    # Fazları doğru ayarla
    if start_epoch >= 10:
        for param in model.parameters():
            param.requires_grad = True
    elif start_epoch >= 5:
        for name, param in model.named_parameters():
            if any(x in name for x in ['blocks.6', 'blocks.5', 'conv_head', 'bn2', 'classifier']):
                param.requires_grad = True

print(f"\n EĞİTİM BAŞLIYOR!")
print(f"   Eğitim : {len(train_dataset)} resim")
print(f"   Test   : {len(val_dataset)} resim")
print(f"   Epoch  : {start_epoch+1} → {TOTAL_EPOCHS}")
print(f"   Cihaz  : {device}")
print()

for epoch in range(start_epoch, TOTAL_EPOCHS):

    #  FAZ GEÇİŞLERİ
    if epoch == 0:
        optimizer = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, model.parameters()),
            lr=1e-3, weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=5)
        print("━"*50)
        print(" FAZ 1 (Epoch 1-5): Sadece classifier, LR=1e-3")
        print("━"*50)

    elif epoch == 5:
        for name, param in model.named_parameters():
            if any(x in name for x in ['blocks.6', 'blocks.5', 'conv_head', 'bn2']):
                param.requires_grad = True
        optimizer = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, model.parameters()),
            lr=5e-5, weight_decay=1e-4
        )
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=5)
        print("\n" + "━"*50)
        print(" FAZ 2 (Epoch 6-10): Son bloklar açıldı, LR=5e-5")
        print("━"*50)

    elif epoch == 10:
        for param in model.parameters():
            param.requires_grad = True
        optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)
        print("\n" + "━"*50)
        print(" FAZ 3 (Epoch 11-20): Tüm model, LR=1e-5")
        print("━"*50)

    #  EĞİTİM
    model.train()
    train_loss = 0
    train_correct = 0
    train_total = 0
nu
    for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1:2d}/{TOTAL_EPOCHS} [Eğitim]"):
        labels = (labels == fake_idx).float()
        imgs = imgs.to(device)
        labels = labels.to(device).unsqueeze(1)

        optimizer.zero_grad()
        out = model(imgs)
        loss = criterion(out, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()

        preds = (torch.sigmoid(out) > 0.5).float()
        train_correct += (preds == labels).sum().item()
        train_total += labels.size(0)

    scheduler.step()
    train_acc = train_correct / max(train_total, 1) * 100

    model.eval()
    v_preds, v_targets = [], []

    with torch.no_grad():
        for imgs, labels in tqdm(val_loader, desc=f"Epoch {epoch+1:2d}/{TOTAL_EPOCHS} [Test  ]"):
            labels = (labels == fake_idx).float()
            probs = torch.sigmoid(model(imgs.to(device))).cpu().numpy()
            v_preds.extend(probs.flatten())
            v_targets.extend(labels.numpy())

    auc = roc_auc_score(v_targets, v_preds)
    val_acc = accuracy_score(v_targets, [1 if p > 0.5 else 0 for p in v_preds]) * 100
    avg_loss = train_loss / len(train_loader)
    current_lr = optimizer.param_groups[0]['lr']
    pred_std = np.std(v_preds)
    pred_mean = np.mean(v_preds)

    history.append({
        'epoch': epoch + 1, 'loss': avg_loss,
        'train_acc': train_acc, 'val_acc': val_acc,
        'auc': auc, 'lr': current_lr
    })

    print(f"\n   Epoch {epoch+1}/{TOTAL_EPOCHS}:")
    print(f"     Loss: {avg_loss:.4f} | Train: %{train_acc:.1f} | Val: %{val_acc:.1f} | AUC: {auc:.4f} | LR: {current_lr:.6f}")
    print(f"     Dağılım: mean={pred_mean:.3f}, std={pred_std:.3f}")

    if pred_std < 0.05:
        print(f"      Model kolaps riski! (std={pred_std:.3f})")

    if auc > best_auc:
        best_auc = auc
        early_stop_counter = 0
        torch.save(model.state_dict(), SAVE_PATH)
        print(f"      YENİ EN İYİ! AUC={auc:.4f} → Kaydedildi!")
    else:
        early_stop_counter += 1
        print(f"      İyileşme yok ({early_stop_counter}/{patience})")

    # Checkpoint
    torch.save({
        'epoch': epoch + 1,
        'model_state': model.state_dict(),
        'best_auc': best_auc,
        'early_stop_counter': early_stop_counter,
        'history': history
    }, CHECKPOINT_PATH)
    print(f"      Checkpoint kaydedildi (Epoch {epoch+1})")

    if early_stop_counter >= patience:
        print(f"\n Early Stopping: {patience} epoch iyileşme olmadı.")
        break

print(f"\n Eğitim tamamlandı! En iyi AUC: {best_auc:.4f}")

#  Rapor & Optimal Threshold


print("="*55)
print(" EĞİTİM RAPORU")
print("="*55)

print(f"\n{'Epoch':>5} | {'Loss':>8} | {'Train%':>7} | {'Val%':>6} | {'AUC':>6} | {'LR':>10}")
print("-" * 55)
for h in history:
    print(f"{h['epoch']:>5} | {h['loss']:>8.4f} | {h['train_acc']:>6.2f}% | {h['val_acc']:>5.2f}% | {h['auc']:>6.4f} | {h['lr']:>10.6f}")

print(f"\n En İyi AUC: {best_auc:.4f}")

# En iyi modeli yükle
model.load_state_dict(torch.load(SAVE_PATH, map_location=device))
model.eval()

v_preds_final, v_targets_final = [], []
with torch.no_grad():
    for imgs, labels in val_loader:
        labels = (labels == fake_idx).float()
        probs = torch.sigmoid(model(imgs.to(device))).cpu().numpy()
        v_preds_final.extend(probs.flatten())
        v_targets_final.extend(labels.numpy())

# Skor dağılımları
real_scores = [p for p, t in zip(v_preds_final, v_targets_final) if t == 0]
fake_scores = [p for p, t in zip(v_preds_final, v_targets_final) if t == 1]

print(f"\n GERÇEK videoların skorları:")
if real_scores:
    print(f"   Min: {min(real_scores):.4f}  Max: {max(real_scores):.4f}  Ort: {np.mean(real_scores):.4f}")

print(f" SAHTE videoların skorları:")
if fake_scores:
    print(f"   Min: {min(fake_scores):.4f}  Max: {max(fake_scores):.4f}  Ort: {np.mean(fake_scores):.4f}")

# Optimal threshold bul
best_threshold = 0.5
best_acc = 0
print(f"\n Threshold Tarama:")
print(f"{'Threshold':>10} | {'Accuracy':>10} | {'Durum':>10}")
print("-" * 35)

for t in np.arange(0.20, 0.80, 0.05):
    acc = accuracy_score(v_targets_final, [1 if p > t else 0 for p in v_preds_final])
    marker = ""
    if acc > best_acc:
        best_acc = acc
        best_threshold = t
        marker = " ← EN İYİ"
    print(f"{t:>10.2f} | {acc*100:>9.2f}% |{marker}")

print(f"\n{'='*55}")
print(f" OPTİMAL THRESHOLD: {best_threshold:.2f}")
print(f" Bu threshold ile accuracy: %{best_acc*100:.2f}")
print(f"{'='*55}")
print(f"\n inference_fix.py'de şunu güncelle:")
print(f'   FAKE_THRESHOLD = {best_threshold:.2f}')
print(f'   MODEL_PATH = "{SAVE_PATH}"')

import os
import cv2
import torch
import numpy as np
import timm
from PIL import Image
from torchvision import transforms
from insightface.app import FaceAnalysis


MODEL_PATH = "/content/drive/MyDrive/dfdc_model_v2_best.pth"
TEST_VIDEO_PATH = "/content/WhatsApp Video 2026-06-08 at 22.58.49 (1).mp4"


FAKE_THRESHOLD = 0.20

NUM_FRAMES = 15


def load_model(path):
    """Eğitilmiş modeli yükle"""
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = timm.create_model('efficientnet_b4', pretrained=False, num_classes=1)
    model.load_state_dict(torch.load(path, map_location=device))
    model = model.to(device)
    model.eval()
    print(f" Model yüklendi: {path}")
    print(f" Cihaz: {device}")
    return model, device


def analyze_video(video_path, model, device, face_app, tf, num_frames=15):

    if not os.path.exists(video_path):
        print(f" Video bulunamadı: {video_path}")
        return None, 0

    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    print(f"📹 Video: {total_frames} kare, {fps:.1f} FPS, {total_frames/max(fps,1):.1f} saniye")

    if total_frames <= 0:
        cap.release()
        print(" Video okunamadı!")
        return None, 0

    # Eşit aralıklı kare seçimi
    sample_positions = np.linspace(
        total_frames * 0.1,
        total_frames * 0.9,
        num_frames,
        dtype=int
    )

    frames = []
    for pos in sample_positions:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(pos))
        ret, frame = cap.read()
        if ret:
            frames.append(frame)
    cap.release()

    print(f" {len(frames)} kare okundu.")

    probs = []
    face_count = 0

    for i, frame in enumerate(frames):
        faces = face_app.get(frame)

        if not faces:
            continue

        face_count += 1
        face = max(faces, key=lambda x: (x.bbox[2]-x.bbox[0])*(x.bbox[3]-x.bbox[1]))
        bbox = face.bbox.astype(int)

        size = int(max(bbox[2]-bbox[0], bbox[3]-bbox[1]) * 1.5)
        cx, cy = (bbox[0]+bbox[2])//2, (bbox[1]+bbox[3])//2
        x1 = max(0, cx - size//2)
        y1 = max(0, cy - size//2)
        x2 = min(frame.shape[1], x1 + size)
        y2 = min(frame.shape[0], y1 + size)
        cropped = frame[y1:y2, x1:x2]

        if cropped.size == 0:
            continue

        img_rgb = cv2.cvtColor(cv2.resize(cropped, (256, 256)), cv2.COLOR_BGR2RGB)
        input_t = tf(Image.fromarray(img_rgb)).unsqueeze(0).to(device)

        with torch.no_grad():
            prob = torch.sigmoid(model(input_t)).item()
            probs.append(prob)

    print(f" Yüz bulunan kare: {face_count}/{len(frames)}")
    return probs, face_count


def classify(probs, threshold):
    """
    Skorları analiz edip karar verir.

    Strateji:
    - std > 0.30 → Model tutarsız, oylama kullan
    - std <= 0.30 → Model tutarlı, median kullan
    """
    if not probs:
        return "HATA: Yüz tespit edilemedi", 0.0

    mean_p = float(np.mean(probs))
    median_p = float(np.median(probs))
    std_p = float(np.std(probs))

    fake_votes = sum(1 for p in probs if p > threshold)
    real_votes = len(probs) - fake_votes

    print(f"\n HAM SKORLAR:")
    for i, p in enumerate(probs):
        bar = "" * int(p * 30)
        tag = "SAHTE" if p > threshold else "GERÇEK"
        print(f"  Kare {i+1:2d}: {p:.4f} {bar:<30} [{tag}]")

    print(f"\n Ortalama : {mean_p:.4f}")
    print(f" Medyan   : {median_p:.4f}")
    print(f" Std      : {std_p:.4f}")
    print(f" Oylama   : {real_votes} GERÇEK vs {fake_votes} SAHTE")
    print(f" Eşik     : {threshold}")

    # Karar
    if std_p > 0.30:
        print(f"\n Model tutarsız (std={std_p:.2f}), oylama kullanılıyor...")
        if real_votes > fake_votes:
            return " GERÇEK (REAL) [oylama]", (real_votes / len(probs)) * 100
        elif fake_votes > real_votes:
            return " SAHTE (DEEPFAKE) [oylama]", (fake_votes / len(probs)) * 100
        else:
            return " BELİRSİZ", 50.0
    else:
        if median_p > threshold:
            return " SAHTE (DEEPFAKE)", median_p * 100
        else:
            return " GERÇEK (REAL)", (1 - median_p) * 100


if __name__ == "__main__":
    print(" Sistem hazırlanıyor...\n")

    # InsightFace
    face_app = FaceAnalysis(
        name='buffalo_l',
        providers=['CUDAExecutionProvider', 'CPUExecutionProvider']
    )
    face_app.prepare(ctx_id=0, det_size=(640, 640))

    # Transform
    tf = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    model, device = load_model(MODEL_PATH)

    print(f"\n Analiz ediliyor: {TEST_VIDEO_PATH}")
    probs, face_count = analyze_video(
        TEST_VIDEO_PATH, model, device, face_app, tf, num_frames=NUM_FRAMES
    )

    if probs is None or len(probs) == 0:
        print(f"\n Video analiz edilemedi!")
        print(f" Kontrol et:")
        print(f"   1. Video yolu doğru mu?")
        print(f"   2. Videoda yüz var mı?")
        print(f"   3. Video codec'i destekleniyor mu?")
    else:
        karar, guven = classify(probs, FAKE_THRESHOLD)

        print(f"\n{'='*55}")
        print(f"  KARAR       : {karar}")
        print(f"  GÜVEN SKORU : %{guven:.2f}")
        print(f"{'='*55}")